defaults:
  - _self_
  - data: dataset
  - features: features
  - models: lightgbm
  - hydra: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

output:
  path: output
  submission: sample_submission.csv
  name: 3day-cross-validation-xgboost.csv